version: '3.8'
services:
  trino:
    image: trinodb/trino:latest
    container_name: trino
    hostname: trino
    ports:
      - 8080:8080
    volumes:
      - ./trino:/etc/trino
    depends_on:
      - metastore
    networks:
      - net_lakehouse

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9001/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - net_lakehouse

  metastore-db:
    image: mysql:5.7
    container_name: metastore-db
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=metastore_db
    volumes:
    - metastore-db:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
      - net_lakehouse

  create-metastore-schema:
    image: apache/hive:4.0.0
    container_name: create-metastore-schema
    depends_on:
      - metastore-db
    command: /opt/hive-metastore/bin/schematool --verbose -initSchema -dbType mysql -userName ${MYSQL_ROOT_USER} -passWord ${MYSQL_ROOT_PASSWORD} -url jdbc:mysql://metastore-db:3306/metastore_db?createDatabaseIfNotExist=true
    restart: on-failure
    networks:
      - net_lakehouse

  metastore:
    image: apache/hive:4.0.0
    container_name: metastore
    volumes:
      - ./trino/conf/metastore-site.xml:/opt/hive-metastore/conf/metastore-site.xml
      - ./trino/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
    command: /opt/hive-metastore/bin/start-metastore -p 9083
    depends_on:
      - create-metastore-schema
      - metastore-db
      - minio
    restart: always
    networks:
      - net_lakehouse

volumes:
  metastore-db:
  minio-data:

networks:
  net_lakehouse: