CREATE DATABASE IF NOT EXISTS bronze;
CREATE DATABASE IF NOT EXISTS silver;
CREATE DATABASE IF NOT EXISTS gold;

GRANT ALL PRIVILEGES ON bronze.* TO 'hive'@'%';
GRANT ALL PRIVILEGES ON silver.* TO 'hive'@'%';
GRANT ALL PRIVILEGES ON gold.* TO 'hive'@'%';
FLUSH PRIVILEGES;
